version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.18
    commands:
      - echo Nothing to do in the install phase...

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...

  build:
    commands:
      - echo Build started on `date`
      - GOARCH=amd64
      - GOOS=linux
      - go mod download
      - go run main.go migrate-dev

  post_build:
    commands:
      - echo Nothing to do in the post_build phase...

cache:
  paths:
    - "/go/pkg/mod/**/*"
