TRUNCATE TABLE wellbe_common.c_service;
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(1, 1, 'Private rooms', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(2, 1, 'Women only', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(3, 1, 'Shower', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(4, 1, 'Pick-up service', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(1, 2, '個室あり', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(2, 2, '女性専用', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(3, 2, 'シャワー利用可', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(4, 2, '送迎サービス', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(1, 3, 'Phòng riêng', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(2, 3, 'Dành riêng cho', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(3, 3, 'Có phòng tắm', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(4, 3, 'Dịch vụ đón khách', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(1, 4, '私人房间', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(2, 4, '仅限女性', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(3, 4, '淋浴', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(4, 4, '接机服务', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(1, 5, '私人房間', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(2, 5, '限女性', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(3, 5, '淋浴', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(4, 5, '接機服務', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(1, 6, '개인실', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(2, 6, '여성 전용', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(3, 6, '샤워', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(4, 6, '픽업 서비스', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(1, 7, 'ห้องส่วนตัว', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(2, 7, 'เฉพาะผู้หญิงเท่านั้น', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(3, 7, 'อาบน้ำ', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(4, 7, 'บริการรับ-ส่ง', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(1, 8, 'Bilik persendirian', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(2, 8, 'Perempuan sahaja', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(3, 8, 'Mandi', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(4, 8, 'Perkhidmatan mengambil', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(1, 9, 'Kamar pribadi', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(2, 9, 'Khusus wanita', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(3, 9, 'Mandi', '2001/1/1 0:00', 'DML', '', '');
INSERT INTO wellbe_common.c_service(service_cd, language_cd, service_name, create_datetime, create_function, update_datetime, update_function) VALUES(4, 9, 'Layanan penjemputan', '2001/1/1 0:00', 'DML', '', '');
