package constants

const (
	ENV_KEYWORD = "WELLBE_ENV"
	ENV_LOCAL   = "local"
	ENV_PRODUCT = "product"

	ARGS_KEYWORD_MIGRATE     = "migrate"
	ARGS_KEYWORD_MIGRATE_DEV = "migrate-dev"

	TIME_LOCATION_ASIA_TOKYO           = "Asia/Tokyo"
	DATE_FORMAT                        = "20060102"
	DATE_FORMAT_HYPHEN                 = "2006-01-02"
	DATETIME_FORMAT                    = "20060102150405"
	DATETIME_YYYYMMDDHHCLOLONMM_FORMAT = "2006010215:04"
	DATETIME_DB_MILLSEC_FORMAT         = "2006-01-02 15:04:05.000"
	DATETIME_YYYYMMDDHHMM_FORMAT       = "2006-01-02 15:04"
	TIME_HHMM_FORMAT                   = "15:04"

	API_KEY_REUQEST_HEADER_NAME = "Wellbe_Apikey"
	API_KEY_CLIENT              = "fpbaVPtY4c5ayApcztyfMrFdhmmHAYA"
	API_KEY_BATCH               = "eWKemeo1tm5Q5aoilbMT8fANJkEeTnI"
	API_KEY_API                 = "Bi8tvMPgtleO0n1juL0xp5kxSTxGnYh"

	HTTPS_PROTOCOL                = "https://"
	S3_DOMAIN_SUFFIX              = ".s3"
	AWS_DOMAIN_SUFFIX             = ".amazonaws.com"
	S3_IMAGE_OBJECT_KEY           = "images/"
	S3_IMAGE_OBJECT_KEY_PUBLISHED = "published/"

	NOREPLY_MAIL_ADDRESS = "no-reply@wellbe-asia.com"

	DEFAULT_LANGUAGE_CD                 = "2"
	DEFAULT_CONTACT_MAIL_ADDRESS_WELLBE = "user_contact@realize-wellbe.com"

	LOGIC_ERROR_CODE_SUCCESS                             = 0
	LOGIC_ERROR_CODE_CANNOT_SIGNUP                       = 401 // サインアップ失敗
	LOGIC_ERROR_CODE_CANNOT_LOGIN                        = 402 // ログイン失敗
	LOCIG_ERROR_CODE_TOKEN_PARSE_ERROR                   = 403 // トークンの変換失敗
	LOCIG_ERROR_CODE_CANNOT_CONFIRM_SIGNUP               = 404
	LOCIG_ERROR_CODE_TOKEN_NOTEXISTS                     = 405
	LOCIG_ERROR_CODE_APIKEY_MISMATCH                     = 406
	LOCIG_ERROR_CODE_NEED_LOGIN                          = 407
	LOCIG_ERROR_CODE_TOKEN_ID_MISMATCH_WITH_KEY          = 408
	LOCIG_ERROR_CODE_APIKEY_NOTMATCH                     = 409
	LOGIC_ERROR_CODE_EMAIL_DUPPLICATE                    = 410
	LOGIC_ERROR_CODE_EMAIL_ISNOTEXISTS                   = 411
	LOGIC_ERROR_CODE_CANNOT_CHANGE_EMAIL                 = 412
	LOGIC_ERROR_CODE_CANNOT_CHANGE_PASSWORD              = 413
	LOGIC_ERROR_CODE_SHOP_URL_DUPPLICATE                 = 414
	LOGIC_ERROR_CODE_SHOP_URL_NOT_REGISTERED             = 415
	LOGIC_ERROR_CODE_CONTENTS_URL_DUPPLICATE             = 416
	LOGIC_ERROR_CODE_SHOP_CHECKOUT_TIMING_NOT_REGISTERED = 417
	LOGIC_ERROR_CODE_SHOP_COUPON_NOT_AVAILABLE           = 418
	LOGIC_ERROR_CODE_NOTEXISTS_UPDATE                    = 501
	LOGIC_ERROR_CODE_NOTEXISTS_DELETE                    = 502
	LOGIC_ERROR_CODE_NOTEXISTS_FOREIGN_KEY               = 511
	LOGIC_ERROR_CODE_NOTALLOWED_MENU_FOR_MALE            = 601
	LOGIC_ERROR_CODE_NOTALLOWED_MENU_FOR_FEMALE          = 602
	LOGIC_ERROR_CODE_BOOKING_NOT_AVAILABLE               = 603
	LOGIC_ERROR_CODE_BOOKING_ID_DUPPLICATE               = 604
	LOGIC_ERROR_CODE_ACCOUNT_IS_TEMPORARY                = 605
	LOGIC_ERROR_CODE_ACCOUNT_IS_WITHDRAWN                = 606
	LOGIC_ERROR_CODE_SHOP_LOCATION_NONAVAILABLE          = 607
	LOGIC_ERROR_CODE_CANCEL_LIMIT_EXPIRED                = 608
	LOGIC_ERROR_CODE_PAYMENT_REFUND_NONAVAILABLE         = 609
	LOGIC_ERROR_CODE_BOOKING_LIMIT_EXPIRED               = 610
	LOGIC_ERROR_CODE_BOOKING_ALREADY_CANCELED            = 611
	LOGIC_ERROR_CODE_BOOKING_IS_NOT_EXISTS               = 612
	LOGIC_ERROR_CODE_CHECKOUT_ALREADY                    = 613
	LOGIC_ERROR_CODE_BOOKING_STATUS_IS_REQUEST           = 614
	LOGIC_ERROR_CODE_BOOKING_STATUS_IS_CANCEL            = 615
	LOGIC_ERROR_CODE_BOOKING_STATUS_IS_FIXED             = 616
	LOGIC_ERROR_CODE_NUMBER_OF_BOOKING_LIMIT_OVER        = 617
	LOGIC_ERROR_CODE_SHOPID_NOTMATCH                     = 618
	LOGIC_ERROR_CODE_REVIEW_ALREADY_POSTED               = 619
	LOGIC_ERROR_CODE_SOURCE_DESCRIPTION_NOT_REGISTERED   = 620
	LOGIC_ERROR_CODE_SOURCE_MENU_NOT_REGISTERED          = 621
	LOGIC_ERROR_CODE_CHECKOUT_NOT_AVAILABLE              = 622
	LOGIC_ERROR_CODE_CHECKOUT_NOT_AUTHORIZED             = 623
	LOGIC_ERROR_CODE_INVALID_INVOICE_STATUS              = 624
	LOGIC_ERROR_CODE_PAYPAL_CHECKOUT_DENIED              = 701
	LOGIC_ERROR_CODE_PAYPAL_NOT_CHECKOUT_YET             = 702
	LOGIC_ERROR_CODE_PAYPAL_REFUND_DENIED                = 703
	LOGIC_ERROR_CODE_S3_GET_OBJECT_ERROR                 = 704
	LOGIC_ERROR_CODE_TRANSLATE_ERROR                     = 705
	LOGIC_ERROR_CODE_DBERROR                             = 901
	LOGIC_ERROR_CODE_DATETIME_PARSEERROR                 = 902
	LOGIC_ERROR_CODE_FILEIOERROR                         = 903
	LOGIC_ERROR_CODE_ENCODEERROR                         = 904
	LOGIC_ERROR_CODE_API_INITIATE_ERROR                  = 905
	LOGIC_ERROR_CODE_ENVERROR                            = 906
	LOGIC_ERROR_CODE_NUMBERING_OVERFLOW                  = 907
	LOGIC_ERROR_CODE_NUMBERING_NOTEXISTS                 = 908
	LOGIC_ERROR_CODE_JWK_NOTEXISTS                       = 909
	LOGIC_ERROR_CODE_PAYPAL_APIERROR                     = 910
	LOGIC_ERROR_CODE_MASTER_DATA_IS_UNSETUP              = 911
	LOGIC_ERROR_CODE_COMPARE_STRING_INVALID              = 912
	LOGIC_ERROR_CODE_MAIERERROR                          = 913
	LOGIC_ERROR_CODE_EXCHANGE_PAIRE_IS_UNSETUP           = 914
	LOGIC_ERROR_CODE_API_EXCHANGE_RATE                   = 915
	LOGIC_ERROR_CODE_RECAPTCHA_FAIL                      = 916
	LOGIC_ERROR_CODE_IMAGE_CONVERT                       = 917
	LOGIC_ERROR_CODE_SEVERERROR                          = 990

	WEBAPI_RESPONSE_KEYWORD_STATUS               = "result_code"
	WEBAPI_RESPONSE_KEYWORD_MESSAGE              = "message"
	WEBAPI_RESPONSE_KEYWORD_RESULT_NAME          = "result"
	WEBAPI_RESPONSE_KEYWORD_ONETIME_TOKEN_NAME   = "onetime_token"
	WEBAPI_RESPONSE_KEYWORD_CERTIFIED_TOKEN_NAME = "certified_token"
	NUMBERING_KEY_SHOP_NO                        = "ShopNo"
	NUMBERING_KEY_BOOKING_NO                     = "BookingNo"
	NUMBERING_KEY_ACCOUNT_NO                     = "AccountNo"
	NUMBERING_KEY_CUSTOMER_NO                    = "CustomerNo"
	NUMBERING_KEY_SHOP_CONTACT_NO                = "ShopContactNo"
	NUMBERING_KEY_SHOP_NO_PRE                    = "S-"
	NUMBERING_KEY_BOOKING_NO_PRE                 = "B-"
	NUMBERING_KEY_ACCOUNT_NO_PRE                 = "A-"
	NUMBERING_KEY_CUSTOMER_NO_PRE                = "C-"
	NUMBERING_KEY_SHOP_CONTACT_NO_PRE            = "CC-"

	ENV_WELLBE_COMMON_PORT                     = "WELLBE_COMMON_PORT"
	ENV_WELLBE_COMMON_DB_DRIVER                = "WELLBE_COMMON_DB_DRIVER"
	ENV_WELLBE_COMMON_DB_DSN                   = "WELLBE_COMMON_DB_DSN"
	ENV_WELLBE_COMMON_MAILER_DOMAIN            = "WELLBE_COMMON_MAILER_DOMAIN"
	ENV_WELLBE_COMMON_REGION_NAME              = "WELLBE_COMMON_REGION_NAME"
	ENV_WELLBE_COMMON_CREDENTIAL_PROFILER_NAME = "WELLBE_COMMON_CREDENTIAL_PROFILER_NAME"
	ENV_WELLBE_COMMON_S3_STATIC_BUCKET_NAME    = "WELLBE_COMMON_S3_STATIC_BUCKET_NAME"
	ENV_WELLBE_COMMON_DB_MAX_OPEN_CONNECTIONS  = "WELLBE_COMMON_DB_MAX_OPEN_CONNECTIONS"
	ENV_WELLBE_COMMON_DB_MAX_IDLE_CONNECTIONS  = "WELLBE_COMMON_DB_MAX_IDLE_CONNECTIONS"
	ENV_WELLBE_COMMON_DB_MAX_LIFETIME_MINUTES  = "WELLBE_COMMON_DB_MAX_LIFETIME_MINUTES"
	ENV_WELLBE_COMMON_RECAPTCHA_SECRET_KEY     = "WELLBE_COMMON_RECAPTCHA_SECRET_KEY"
	ENV_WELLBE_COMMON_IMAGE_DOMAIN             = "WELLBE_COMMON_IMAGE_DOMAIN"
	ENV_WELLBE_COMMON_IMGIX_DOMAIN             = "WELLBE_COMMON_IMGIX_DOMAIN"
	ENV_WELLBE_AWS_CONFIGURE_LOCAL             = "WELLBE_AWS_CONFIGURE_LOCAL"
	ENV_WELLBE_AWS_TRANSLATE_STAB              = "WELLBE_AWS_TRANSLATE_STAB"

	ENV_WELLBE_COMMON_DB_DOMAIN   = "WELLBE_COMMON_DB_DOMAIN"
	ENV_WELLBE_COMMON_DB_PORT     = "WELLBE_COMMON_DB_PORT"
	ENV_WELLBE_COMMON_DB_USER     = "WELLBE_COMMON_DB_USER"
	ENV_WELLBE_COMMON_DB_PASSWORD = "WELLBE_COMMON_DB_PASSWORD"
	ENV_WELLBE_COMMON_DB_DBNAME   = "WELLBE_COMMON_DB_DBNAME"

	ENV_WELLBE_AWS_CONFIGURE_LOCAL_TRUE = "True"
	ENV_WELLBE_AWS_TRANSLATE_STAB_TRUE  = "True"

	COMPARE_BEFORE = "<"
	COMPARE_AFTER  = ">"
	COMPARE_EQUAL  = "="

	RANDOM_NUMBER_DIGIT = 3

	IANA_TIMEZONE_UTC = "Etc/UTC"

	EXTENTION_WEBP = ".webp"
	EXTENTION_PNG  = ".png"
	EXTENTION_JPG  = ".jpg"
	EXTENTION_JPEG = ".jpeg"
	MIME_WEBP      = "image/webp"

	TRANSLATE_CUSTOM               = "custom_translate"
	TRANSLATE_SHOP                 = "custom_translate_shop"
	TRANSLATE_MERGE_STRATEGY       = "OVERWRITE"
	TRANSLATE_DIRECTIONALITY_MULTI = "MULTI"
	TRANSLATE_FILE_FORMAT_CSV      = "CSV"
)