package cMailTemplate

const (
	BOOKING_ACCEPT                 = 1
	CANCEL_REQUEST                 = 2
	AUTO_CANCEL                    = 3
	PAYOUT_NOTIFY                  = 4
	PAYMENT_FAILED                 = 5
	REQUEST_BOOKING_ACCEPT         = 6
	COMPLETE_ACCOUNT_REGISTERATION = 7
	WITHDRAWN_COMPLETE             = 8
	CANCEL_REQUEST_BY_SHOP         = 9
	AUTO_CANCEL_REQUEST_EXPIRE     = 10
	SHOP_BOOKING_ACCEPT_REQUEST    = 11
	SHOP_BOOKING_ACCEPT            = 12
	SHOP_BOOKING_APPROVED          = 13
	USER_CONTACT_TO_WELLBE         = 14
	REVIEW_REQUEST                 = 15
	CHECKOUT_REQUEST_RESENT        = 16
	BOOKING_CANCEL_TO_SHOP         = 17
	CHECKOUT_ANNOUNCEMENT          = 18
	CHECKOUT_ANNOUNCEMENT_REQUEST  = 19
)